# Generated by Django 6.0 on 2025-12-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
